### ISSUE TITLE
Error of listing protocols

### ISSUE THREAD

**Issue by alartin** [nanoporetech/minknow_lims_interface#1]
Hi,
I tried to mimic the demo of list devices with list protocols, but it threw error like this:
```
<class 'minknow.rpc.protocol_pb2.ListProtocolsRequest'>

Traceback (most recent call last):

  File "list_protocols.py", line 54, in <module>

    response = stub.list_protocols(list_request)

  File "/software/anaconda3/envs/minknowapi/lib/python3.7/site-packages/grpc/_channel.py", line 533, in __call__

    return _end_unary_response_blocking(state, call, False, None)

  File "/software/anaconda3/envs/minknowapi/lib/python3.7/site-packages/grpc/_channel.py", line 467, in _end_unary_response_blocking

    raise _Rendezvous(state, None, None, deadline)

grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:

        status = StatusCode.UNIMPLEMENTED

        details = ""

        debug_error_string = "{"created":"@1564651228.763251169","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1017,"grpc_message":"","grpc_status":12}"
```
My code is as below:

```

import os

import sys

sys.path.append(os.path.join(os.path.dirname(__file__), "generated"))



# Then import the generated api

import minknow.rpc.protocol_pb2 as protocol

import minknow.rpc.protocol_pb2_grpc as protocol_grpc


# Import the grpc libraries we installed earlier

import grpc

# Connect to the running Manager instance:

#

# We can connect to minknow manager on port 9501.

#

channel = grpc.insecure_channel('localhost:9501')

stub = protocol_grpc.ProtocolServiceStub(channel)


# Send the list request

list_request = protocol.ListProtocolsRequest()

print(type(list_request))

response = stub.list_protocols(list_request)

```
Could you please help?

**Comment by 0x55555555** [comment]
Hi @alartin,

The issue here is you are requesting the protocol list from the port `9501`, this port only serves the manager apis, which can then be used to find ports for individual minknow instances.

In the original example we use the manager api to find the first connected device, and then use that to create a second channel on a different port: https://github.com/nanoporetech/minknow_lims_interface/blob/master/examples/start_protocol.py#L78

**Comment by alartin** [comment]
@jorj1988 You are right! Thanks for the tip!

**Comment by alartin** [comment]
@jorj1988 You are right! Thanks for the tip!
