### ISSUE TITLE
StatusCode.UNIMPLEMENTED

### ISSUE THREAD

**Issue by svennd** [nanoporetech/minknow_lims_interface#2]
Hey,

This is more of a support question, I was playing with the beta device before and this code worked (the entire script is longer) on the new promethion 24 however this fails to run; has this changed ?
script : 

```#-------------------------------------------------------------------------------
# Now python can import the generated api:
#
# First we add the directory we generated into to the python path
import os
import sys
sys.path.append(os.path.join(os.path.dirname(__file__), "generated"))

# Then import the generated api
import minknow.rpc.manager_pb2 as manager
import minknow.rpc.manager_pb2_grpc as manager_grpc
import minknow.rpc.device_pb2 as devicex
import minknow.rpc.device_pb2_grpc as devicex_grpc
import minknow.rpc.instance_pb2 as instance
import minknow.rpc.instance_pb2_grpc as instance_grpc
import minknow.rpc.acquisition_pb2 as acquisition
import minknow.rpc.acquisition_pb2_grpc as acquisition_grpc

from pprint import pprint

# Import the grpc libraries we installed earlier
import grpc
#-------------------------------------------------------------------------------


#-------------------------------------------------------------------------------
# Connect to the running Manager instance:
#
# We can connect to minknow manager on port 9501.
#
channel = grpc.insecure_channel('IP:9501')
stub = manager_grpc.ManagerServiceStub(channel)
#-------------------------------------------------------------------------------

print("================ MANAGER =====================")
print("basecaller_api")
msg = manager.BasecallerApiRequest()
answer = stub.basecaller_api (msg)
pprint(answer)

print("get_version_info")
msg = manager.GetVersionInfoRequest()
answer = stub.get_version_info (msg)
pprint(answer)


print("describe_host")
host_req = manager.DescribeHostRequest()
rep = stub.describe_host(host_req)
pprint(rep)


print("watch_flow_cell_positions")
stream = manager.WatchFlowCellPositionsRequest()
res =  stub.watch_flow_cell_positions (stream)
pprint (res)
```

output : 
```
[root@prom4 examples]# python3 promethion.py
================ MANAGER =====================
get_version_info
Traceback (most recent call last):
  File "promethion.py", line 43, in <module>
    answer = stub.get_version_info (msg)
  File "/usr/local/lib64/python3.6/site-packages/grpc/_channel.py", line 826, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/usr/local/lib64/python3.6/site-packages/grpc/_channel.py", line 729, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNIMPLEMENTED
        details = ""
        debug_error_string = "{"created":"@1596551114.702070615","description":"Error received from peer ipv4:IP:9501","file":"src/core/lib/surface/call.cc","file_line":1055,"grpc_message":"","grpc_status":12}"
```

**Comment by 0x55555555** [comment]
Hi @svennd,

With MinKNOW 20.06 the API compatibility was broken, it sounds likely the promethion is running 20.06 (minknow core 4.0?).

You can find the new minknow api here: https://github.com/nanoporetech/minknow_api

or you can now install it from pypi: 

```
> pip install minknow_api
```

The api is now in its own module `minknow_api` - so some code will need updating.

**Comment by svennd** [comment]
Ah, that does explain allot, yes the box is rather new; Will be trying, thanks for the support!
